In [1]:
import numpy as np
import pandas as pd
from matplotlib.image import imread

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [7]:
a1.shape

(3,)

In [4]:
a2 = np.array([[1, 2, 3],
             [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a2.shape

(2, 3)

In [11]:
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
a3.shape

(1, 3, 3)

In [21]:
a1.ndim, a1.size, a1.shape, type(a1), a1.dtype

(1, 3, (3,), numpy.ndarray, dtype('int32'))

In [22]:
a2.ndim, a2.size, a2.shape, type(a2), a2.dtype

(2, 6, (2, 3), numpy.ndarray, dtype('int32'))

In [23]:
a3.ndim, a3.size, a3.shape, type(a3), a3.dtype

(3, 9, (1, 3, 3), numpy.ndarray, dtype('int32'))

In [20]:
a1.datatype

AttributeError: 'numpy.ndarray' object has no attribute 'datatype'

In [24]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [27]:
ones = np.ones((10, 2))
ones.shape

(10, 2)

In [28]:
zeros = np.zeros((7, 2, 3))
zeros.shape

(7, 2, 3)

In [29]:
a1 = np.arange(0, 100, 3)
a1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [31]:
a1 = np.random.randint(10, size=(7 ,2))
a1

array([[6, 1],
       [7, 3],
       [9, 9],
       [2, 6],
       [5, 2],
       [3, 5],
       [9, 2]])

In [33]:
a1 = np.random.random((3, 5))
a1

array([[0.71589859, 0.32703566, 0.28973451, 0.63661149, 0.44826894],
       [0.18709442, 0.04222639, 0.08785639, 0.67918519, 0.96463246],
       [0.26144552, 0.26830061, 0.12164647, 0.03139837, 0.23414692]])

In [40]:
np.random.seed(seed=42)

In [41]:
a1 = np.random.randint(10, size=(4, 6))
a1

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [42]:
a1 = np.random.randint(10, size=(3, 7))
a1

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [44]:
np.unique(a1)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [45]:
a1[0]

array([8, 0, 9, 2, 6, 3, 8])

In [46]:
a1[0, 0]

8

In [47]:
a1[1]

array([2, 4, 2, 6, 4, 8, 6])

In [48]:
a1[:1]

array([[8, 0, 9, 2, 6, 3, 8]])

In [49]:
a1[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [51]:
a1[:2, :2]

array([[8, 0],
       [2, 4]])

In [53]:
random_array = np.random.randint(10, size=(3, 5))
ones = np.ones((3 ,5))

In [54]:
random_array, ones

(array([[3, 5, 1, 9, 1],
        [9, 3, 7, 6, 8],
        [7, 4, 1, 4, 7]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [55]:
random_array

array([[3, 5, 1, 9, 1],
       [9, 3, 7, 6, 8],
       [7, 4, 1, 4, 7]])

In [56]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
random_array + ones

array([[ 4.,  6.,  2., 10.,  2.],
       [10.,  4.,  8.,  7.,  9.],
       [ 8.,  5.,  2.,  5.,  8.]])

In [58]:
ones2 = np.ones((5, 3))
ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
ones2 + ones

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [60]:
ones2 + ones.T

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [61]:
ones3 = np.ones((3, 5))
ones3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
ones3 - ones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
ones * ones3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
ones3 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
np.square(ones3)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
np.mean(ones3)

1.0

In [68]:
np.max(ones3)

1.0

In [69]:
np.min(ones3)

1.0

In [70]:
np.std(ones3)

0.0

In [71]:
np.var(ones3)

0.0

In [73]:
ones3 = ones3.reshape((3, 5, 1))

In [74]:
ones3.shape

(3, 5, 1)

In [75]:
ones3.T.shape

(1, 5, 3)

In [76]:
a1 = np.random.randint(10, size=(3, 3))
a2 = np.random.randint(10, size=(3, 2))

In [77]:
np.dot(a1, a2)

array([[135,  79],
       [ 58,  12],
       [ 70,  56]])

In [78]:
a3 = np.random.randint(10, size=(4, 3))
a4 = np.random.randint(10, size=(4, 3))

In [79]:
np.dot(a3, a4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [80]:
np.dot(a3, a4.T)

array([[ 40,  36,  10,  12],
       [153, 111,  57,  60],
       [140, 100,  52,  56],
       [ 48,  30,  37,  18]])

In [81]:
a3 > a4

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [82]:
a3 >= a4

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [83]:
a3 > 7

array([[False, False, False],
       [ True, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [84]:
a3 == a4

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [85]:
np.sort(a3)

array([[0, 2, 4],
       [6, 9, 9],
       [6, 8, 8],
       [0, 1, 7]])

In [86]:
np.argsort(a3)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [2, 1, 0]], dtype=int64)

In [87]:
np.argmax(a3)

3

In [88]:
a3

array([[2, 0, 4],
       [9, 6, 9],
       [8, 6, 8],
       [7, 1, 0]])

In [89]:
np.argmax(a3, axis=0)

array([1, 1, 1], dtype=int64)

In [90]:
np.argmax(a3, axis=1)

array([2, 0, 0, 0], dtype=int64)

In [91]:
np.argmin(a3, axis=0)

array([0, 0, 3], dtype=int64)

In [92]:
np.argmin(a3, axis=1)

array([1, 1, 1, 2], dtype=int64)

In [95]:
np.random.normal((5, 3))

array([2.3802549, 3.8219025])

In [96]:
np.linspace(1, 100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])